critical_rules <- c(
  lintr::absolute_path_linter(), lintr::any_duplicated_linter(),
  lintr::any_is_na_linter(), lintr::assignment_linter(), lintr::backport_linter(),
  lintr::brace_linter(), lintr::class_equals_linter(), lintr::commas_linter(),
  lintr::commented_code_linter(), lintr::condition_message_linter(),
  lintr::conjunct_test_linter(), lintr::consecutive_assertion_linter(),
  lintr::duplicate_argument_linter(), lintr::empty_assignment_linter(),
  lintr::equals_na_linter(), lintr::expect_comparison_linter(),
  lintr::expect_identical_linter(), lintr::expect_not_linter(),
  lintr::expect_null_linter(), lintr::expect_s3_class_linter(),
  lintr::expect_s4_class_linter(), lintr::expect_true_false_linter(),
  lintr::expect_type_linter(), lintr::fixed_regex_linter(),
  lintr::for_loop_index_linter(), lintr::function_left_parentheses_linter(),
  lintr::function_return_linter(), lintr::if_not_else_linter(),
  lintr::ifelse_censor_linter(), lintr::implicit_assignment_linter(),
  lintr::indentation_linter(), lintr::infix_spaces_linter(),
  lintr::inner_combine_linter(), lintr::is_numeric_linter(),
  lintr::keyword_quote_linter(), lintr::length_levels_linter(),
  lintr::length_test_linter(), lintr::lengths_linter(),
  lintr::library_call_linter(), lintr::literal_coercion_linter(),
  lintr::missing_argument_linter(), lintr::missing_package_linter(),
  lintr::namespace_linter(), lintr::nested_ifelse_linter(),
  lintr::nonportable_path_linter(), lintr::numeric_leading_zero_linter(),
  lintr::object_length_linter(), lintr::object_usage_linter(),
  lintr::outer_negation_linter(), lintr::package_hooks_linter(),
  lintr::paren_body_linter(), lintr::paste_linter(), lintr::pipe_call_linter(),
  lintr::pipe_consistency_linter(), lintr::pipe_continuation_linter(),
  lintr::quotes_linter(), lintr::redundant_equals_linter(),
  lintr::redundant_ifelse_linter(), lintr::regex_subset_linter(),
  lintr::repeat_linter(), lintr::routine_registration_linter(),
  lintr::scalar_in_linter(), lintr::semicolon_linter(), lintr::sort_linter(),
  lintr::spaces_inside_linter(), lintr::spaces_left_parentheses_linter(),
  lintr::sprintf_linter(), lintr::string_boundary_linter(),
  lintr::strings_as_factors_linter(), lintr::system_file_linter(),
  lintr::T_and_F_symbol_linter(), lintr::undesirable_function_linter(),
  lintr::undesirable_operator_linter(),
  lintr::unnecessary_concatenation_linter(), lintr::unnecessary_lambda_linter(),
  lintr::unnecessary_nested_if_linter(),
  lintr::unnecessary_placeholder_linter(), lintr::unreachable_code_linter(),
  lintr::unused_import_linter(), lintr::vector_logic_linter(),
  lintr::whitespace_linter(), lintr::yoda_test_linter()
)

expect_silent(
  print(lintr::lint_package(linters = critical_rules, show_progress = FALSE))
)
