# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

admm_MADMMplasso_cpp <- function(beta0, theta0, beta, beta_hat, theta, rho1, X, Z, max_it, W_hat, XtY, y, N, e_abs, e_rel, alpha, lambda, alph, svd_w, tree, invmat, gg, my_print = TRUE) {
    .Call(`_MADMMplasso_admm_MADMMplasso_cpp`, beta0, theta0, beta, beta_hat, theta, rho1, X, Z, max_it, W_hat, XtY, y, N, e_abs, e_rel, alpha, lambda, alph, svd_w, tree, invmat, gg, my_print)
}

model_intercept <- function(beta0, theta0, beta, theta, X, Z) {
    .Call(`_MADMMplasso_model_intercept`, beta0, theta0, beta, theta, X, Z)
}

modulo <- function(x, n) {
    .Call(`_MADMMplasso_modulo`, x, n)
}

multiples_of <- function(x, divisor, subset_out = FALSE) {
    .Call(`_MADMMplasso_multiples_of`, x, divisor, subset_out)
}

scale_cpp <- function(x, scale) {
    .Call(`_MADMMplasso_scale_cpp`, x, scale)
}

sqrt_sum_squared_rows <- function(x) {
    .Call(`_MADMMplasso_sqrt_sum_squared_rows`, x)
}

